### PR TITLE
make target folder, un-localize filename, use mimetype for guessing

### PR DESCRIPTION
**Pull request by AlexanderWillner**

### CODE REVIEW

**Comment by LRGH** [comment]
Thank you.
There is at least one thing that you broke with this pull request, the `base_filename` which needs to be deduced from the locale.
Do you think that you can add a patch that takes the locale into account, or should I work on it?

**Comment by AlexanderWillner** [comment]
I was *assuming* that the file is stored in english and just localized later on. But it seems indeed that the actual file name depends on the current language setting. Which is weird to say the least... 

E.g. changing the language enforces Mail.app to re-download the attachments. After testing, I've now, for the very same message, the file `Mail-Anhang.gif` (German) and `Mail Attachment.gif` (English). This is not an optimal implementation.

However, I shortly scanned /Application/Mail.app but couldn't find where the strings are stored...

**Comment by LRGH** [comment]
Hum... if the current language is not sufficient, then we need to test all possibilities. I agree that this is not an optimal representation.

**Comment by AlexanderWillner** [comment]
I think I found the relevant list of strings at `/System/Library/PrivateFrameworks/Notes.framework/Versions/A/Resources/*.lproj/MailCore.strings`...

**Comment by LRGH** [comment]
Yes, indeed. It is `MimeAttachmentFilename`. We can parse these files to extract the information.
I prefer that we hardcode it in the python source code, to be able to run it on any OS.

**Comment by LRGH** [comment]
I looked at what mimetypes.guess_extension returns, and in fact it is less precise than the table I made.
For example, when the mime-type is `image/jpeg` it returns `.jpe` while for emlx decoding it should be `.jpeg`.
I prefer to revert to a hardcoded table, until we find in OSX where the conversion is decided.

**Comment by AlexanderWillner** [comment]
We can configure mimetypes, so adding your hard coded table as a configuration probably makes most sense.

**Comment by AlexanderWillner** [comment]
Probably hard coding the MimeAttachmentFilename in a table is safe enough.

**Pull request merged**
